CREATE TABLE PRODUCTS (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR NOT NULL CHECK (name <> ''),
    price INTEGER NOT NULL CHECK (price >= 0),
    quantity INTEGER NOT NULL CHECK (quantity >= 0)
);

CREATE TABLE CUSTOMERS (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR NOT NULL CHECK (email <> '')
);

CREATE TABLE ORDERS (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    customerid INTEGER NOT NULL REFERENCES CUSTOMERS(id),
    ordertimestamp TIMESTAMP NOT NULL
);

CREATE TABLE ORDEREDPRODUCTS (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    productid INTEGER NOT NULL REFERENCES PRODUCTS(id),
    orderid INTEGER NOT NULL REFERENCES ORDERS(id),
    price INTEGER NOT NULL CHECK (price >= 0),
    quantity INTEGER NOT NULL CHECK (quantity >= 1)
);

CREATE TABLE IDEMPOTENCYKEYS (
    uuid UUID PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIME
);
